criaCartao(
    'MUNDO AUTOMOTIVO',
    'O QUE É TORQUE EM UM MOTOR?',
    'É A FORÇA DE ROTAÇÃO QUE O MOTOR APLICA ÀS RODAS. QUANTO MAIOR O TORQUE, MAIS FORÇA O VEÍCULO TEM PARA MOVER CARGAS E SUBIR INCLINAÇÕES.'
)

criaCartao(
    'MUNDO AUTOMOTIVO',
    'QUAL É A FUNÇÃO DO SISTEMA ABS?',
    'O ABS (ANTI-LOCK BRAKING SYSTEM) IMPEDE QUE AS RODAS TRAVEM DURANTE A FRENAGEM, PERMITINDO QUE O MOTORISTA MANTENHA O CONTROLE E A DIREÇÃO DO VEÍCULO.'
)

criaCartao(
    'MUNDO AUTOMOTIVO',
    'COMO FUNCIONA A INJEÇÃO ELETRÔNICA DE COMBUSTÍVEL?',
    'SENSORES MONITORAM O MOTOR E AJUSTAM A QUANTIDADE DE COMBUSTÍVEL INJETADO, MELHORANDO A EFICIÊNCIA E REDUZINDO AS EMISSÕES DE POLUENTES.'
)

criaCartao(
    'MUNDO AUTOMOTIVO',
    'O QUE É A POTÊNCIA DE UM MOTOR?',
    'É A CAPACIDADE DE TRABALHO DO MOTOR EM RELAÇÃO AO TEMPO, MEDIDA EM CAVALOS DE POTÊNCIA (CV). QUANTO MAIOR A POTÊNCIA, MAIS RÁPIDO O VEÍCULO PODE ACELERAR.'
)